url: https://egylandscapeproject.github.io/EGYLandscapeProject_website
baseurl: /EGYLandscapeProject_website/

# Site settings
title: EGYLandscape Project
email: EGYLandscapeProject@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Nicolas Michel
  pic: 3
  position: Project Coordinator
  social:
    - title: website
      url: http://iremam.cnrs.fr/spip.php?article68&lang=fr

- name: Albrecht Fuess
  pic: 3
  position: Project Coordinator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Anthony T. Quickel
  pic: 3
  position: Project Assistant Coordinator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Muhammad H. Shaaban
  pic: 3
  position: Project Assistant Coordinator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ghislaine Alleaume
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Julien Loiseau
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Clément Onimus
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Yossef Rapoport
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Kurt Franz
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Astrid Meier
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Bethany Walker
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Kondrad Hirschler
  pic: 3
  position: Direct Participant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Emad Abu Ghazi
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Adam Sabra
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Alan Mikhail
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Wakako Kumakura
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Stuart Borsch
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Zoe Griffith
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Magdi Guirguis
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Dalia Hussein
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Mathieu Eychenne
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Robin Seignobos
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Daisuke Igarashi
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Alison L. Gascoigne
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Heba Saad Abdelnaby
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Aleksandar Shopov
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Gregory Williams
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ahmed Abdel Moniem
  pic: 3
  position: Contributor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/EGYLandscape
  - title: facebook
    url: https://www.facebook.com/EGYLandscapeProject/
  - title: github
    url: https://github.com/egylandscapeproject/

# Postal address (add as many lines as necessary)
address:
  - line:


# Build settings
markdown: kramdown
permalink: pretty
